### ISSUE TITLE
Create a new Next.js project

### ISSUE THREAD

**Issue by yamamurc** [yamamurc/next-template-with-typescript#1]
## OverView

Create a new project for Next.js application using `create-next-app`.

## Description

I'd like to use `npm` for package manager and also TypeScript.

## Tasks

- [x] Run the command to create a new project:
```sh
npx create-next-app next-template-with-typescript --use-npm --typescript
```
- [x] Run the command to add a new remote: 
 ```sh
git remote add origin git@github.com:yamamurc/next-template-with-typescript.git
```
- [x] Run the command to set the remote as upstream branch:
```sh
git push --set-upstream origin main
```
