### ISSUE TITLE
Introduce ESLint, Stylelint and Prettier

### ISSUE THREAD

**Issue by yamamurc** [yamamurc/next-template-with-typescript#4]
## Overview
Introduce some automated lint tools (ESLint, Stylelint) and a code formatter (Prettier).

## Description

I'd like to keep a codebase clean. They can help make it easy.

## Tasks

- [x] Set up ESLint.
  - [x] Install packages:
    - [x] `@typescript-eslint/parser`
    - [x] `@typescript-eslint/eslint-plugin` 
  - [x]  Add `.eslintrc.js.` insted of `.eslintrc.json`
- [x] Set up Stylelint.
  - [x] Install packages:
    - [x] `stylelint`
    - [x] `stylelint-order`
    - [x] `stylelint-config-standard`
    - [x] `stylelint-config-recess-order`
  - [x] Add `stylelintrc.js`.
- [x] Set up Prettier.
  - [x] Install packages:
    - [x] `prettier`
    - [x] `eslint-config-prettier`
  - [x] Add `prettierrc.js`.
- [x] Add VSCode configration files.
  - [x] Make .`vscode` folder.
  - [x] Add `extensions.json` inside `.vscode` folder.
  - [x] Add `.settings.json` inside `.vscode` folder.
